pmOnFail: ignore

minimumReleaseAgeExclude:
  - '@next/*'
  - next
  - '@anthropic-ai/sdk@0.132.0'
  - '@supabase/auth-js@2.117.3'
  - '@supabase/functions-js@2.117.3'
  - '@supabase/postgrest-js@2.117.3'
  - '@supabase/realtime-js@2.117.3'
  - '@supabase/storage-js@2.117.3'
  - '@supabase/supabase-js@2.117.3'
